package com.integrixs.adapters.social.base;

/**
 * Event types for social media adapters
 */
public enum EventType {
    // Social Media Events
    SOCIAL_MEDIA_POST,
    SOCIAL_MEDIA_BOARD,
    SOCIAL_MEDIA_ANALYTICS,
    SOCIAL_MEDIA_CAMPAIGN,
    SOCIAL_MEDIA_AD,
    SOCIAL_MEDIA_FOLLOW,
    SOCIAL_MEDIA_MESSAGE,
    SOCIAL_MEDIA_COMMENT,
    SOCIAL_MEDIA_LIKE,
    SOCIAL_MEDIA_SHARE,
    SOCIAL_MEDIA_USER,
    SOCIAL_MEDIA_MENTION,
    SOCIAL_MEDIA_STORY,
    SOCIAL_MEDIA_REEL,
    SOCIAL_MEDIA_VIDEO,
    SOCIAL_MEDIA_IMAGE,

    // Collaboration Events
    COLLABORATION_MESSAGE,
    COLLABORATION_FILE,
    COLLABORATION_USER,
    COLLABORATION_CHANNEL,
    COLLABORATION_REACTION,
    COLLABORATION_MENTION,
    COLLABORATION_THREAD,

    // Generic Events
    ADAPTER_CONNECTED,
    ADAPTER_DISCONNECTED,
    ADAPTER_ERROR,
    ADAPTER_WARNING
}
