-- Create Camunda BPM schema tables for process engine
-- This migration creates the core tables needed by Camunda BPM 7.20
-- Note: Camunda can auto-create these, but we're adding them explicitly for better control

-- Engine configuration table
CREATE TABLE IF NOT EXISTS ACT_GE_PROPERTY (
    NAME_ VARCHAR(64),
    VALUE_ VARCHAR(300),
    REV_ INTEGER,
    PRIMARY KEY (NAME_)
);

-- Deployment table
CREATE TABLE IF NOT EXISTS ACT_RE_DEPLOYMENT (
    ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    DEPLOY_TIME_ TIMESTAMP(3),
    SOURCE_ VARCHAR(255),
    TENANT_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
);

-- Process definition table
CREATE TABLE IF NOT EXISTS ACT_RE_PROCDEF (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    CATEGORY_ VARCHAR(255),
    NAME_ VARCHAR(255),
    KEY_ VARCHAR(255),
    VERSION_ INTEGER NOT NULL,
    DEPLOYMENT_ID_ VARCHAR(64),
    RESOURCE_NAME_ VARCHAR(4000),
    DGRM_RESOURCE_NAME_ VARCHAR(4000),
    HAS_START_FORM_KEY_ BOOLEAN,
    SUSPENSION_STATE_ INTEGER,
    TENANT_ID_ VARCHAR(64),
    VERSION_TAG_ VARCHAR(64),
    HISTORY_TTL_ INTEGER,
    PRIMARY KEY (ID_)
);

-- Process instance table
CREATE TABLE IF NOT EXISTS ACT_RU_EXECUTION (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    PROC_INST_ID_ VARCHAR(64),
    BUSINESS_KEY_ VARCHAR(255),
    PARENT_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    SUPER_EXEC_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    IS_ACTIVE_ BOOLEAN,
    IS_CONCURRENT_ BOOLEAN,
    IS_SCOPE_ BOOLEAN,
    IS_EVENT_SCOPE_ BOOLEAN,
    IS_MI_ROOT_ BOOLEAN,
    SUSPENSION_STATE_ INTEGER,
    CACHED_ENT_STATE_ INTEGER,
    TENANT_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    START_TIME_ TIMESTAMP(3),
    START_USER_ID_ VARCHAR(255),
    LOCK_TIME_ TIMESTAMP(3),
    IS_SUB_PROCESS_INSTANCE_ BOOLEAN,
    SUB_CASE_INST_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
);

-- Task table
CREATE TABLE IF NOT EXISTS ACT_RU_TASK (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    CASE_EXECUTION_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    CASE_DEF_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    TASK_DEF_KEY_ VARCHAR(255),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    DELEGATION_ VARCHAR(64),
    PRIORITY_ INTEGER,
    CREATE_TIME_ TIMESTAMP(3),
    DUE_DATE_ TIMESTAMP(3),
    FOLLOW_UP_DATE_ TIMESTAMP(3),
    SUSPENSION_STATE_ INTEGER,
    TENANT_ID_ VARCHAR(64),
    FORM_KEY_ VARCHAR(255),
    PRIMARY KEY (ID_)
);

-- Variable instance table
CREATE TABLE IF NOT EXISTS ACT_RU_VARIABLE (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    NAME_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE PRECISION,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    VAR_SCOPE_ VARCHAR(64),
    SEQUENCE_COUNTER_ BIGINT,
    IS_CONCURRENT_LOCAL_ BOOLEAN,
    TENANT_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
);

-- Job definition table
CREATE TABLE IF NOT EXISTS ACT_RU_JOBDEF (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    PROC_DEF_ID_ VARCHAR(64),
    PROC_DEF_KEY_ VARCHAR(255),
    ACT_ID_ VARCHAR(255),
    JOB_TYPE_ VARCHAR(255) NOT NULL,
    JOB_CONFIGURATION_ VARCHAR(255),
    SUSPENSION_STATE_ INTEGER,
    JOB_PRIORITY_ BIGINT,
    TENANT_ID_ VARCHAR(64),
    DEPLOYMENT_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
);

-- Job table
CREATE TABLE IF NOT EXISTS ACT_RU_JOB (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    TYPE_ VARCHAR(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP(3),
    LOCK_OWNER_ VARCHAR(255),
    EXCLUSIVE_ BOOLEAN,
    EXECUTION_ID_ VARCHAR(64),
    PROCESS_INSTANCE_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    PROC_DEF_KEY_ VARCHAR(255),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ VARCHAR(64),
    EXCEPTION_MSG_ VARCHAR(4000),
    DUEDATE_ TIMESTAMP(3),
    REPEAT_ VARCHAR(255),
    HANDLER_TYPE_ VARCHAR(255),
    HANDLER_CFG_ VARCHAR(4000),
    DEPLOYMENT_ID_ VARCHAR(64),
    SUSPENSION_STATE_ INTEGER NOT NULL DEFAULT 1,
    JOB_DEF_ID_ VARCHAR(64),
    PRIORITY_ BIGINT NOT NULL DEFAULT 0,
    SEQUENCE_COUNTER_ BIGINT,
    TENANT_ID_ VARCHAR(64),
    CREATE_TIME_ TIMESTAMP(3),
    PRIMARY KEY (ID_)
);

-- External task table
CREATE TABLE IF NOT EXISTS ACT_RU_EXT_TASK (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    WORKER_ID_ VARCHAR(255),
    TOPIC_NAME_ VARCHAR(255),
    RETRIES_ INTEGER,
    ERROR_MSG_ VARCHAR(4000),
    ERROR_DETAILS_ID_ VARCHAR(64),
    LOCK_EXP_TIME_ TIMESTAMP(3),
    SUSPENSION_STATE_ INTEGER,
    EXECUTION_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    PROC_DEF_KEY_ VARCHAR(255),
    ACT_ID_ VARCHAR(255),
    ACT_INST_ID_ VARCHAR(64),
    TENANT_ID_ VARCHAR(64),
    PRIORITY_ BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_)
);

-- Incident table
CREATE TABLE IF NOT EXISTS ACT_RU_INCIDENT (
    ID_ VARCHAR(64),
    REV_ INTEGER,
    INCIDENT_TIMESTAMP_ TIMESTAMP(3),
    INCIDENT_MSG_ VARCHAR(4000),
    INCIDENT_TYPE_ VARCHAR(255) NOT NULL,
    EXECUTION_ID_ VARCHAR(64),
    ACTIVITY_ID_ VARCHAR(255),
    PROC_INST_ID_ VARCHAR(64),
    PROC_DEF_ID_ VARCHAR(64),
    CAUSE_INCIDENT_ID_ VARCHAR(64),
    ROOT_CAUSE_INCIDENT_ID_ VARCHAR(64),
    CONFIGURATION_ VARCHAR(255),
    TENANT_ID_ VARCHAR(64),
    JOB_DEF_ID_ VARCHAR(64),
    PRIMARY KEY (ID_)
);

-- History process instance table
CREATE TABLE IF NOT EXISTS ACT_HI_PROCINST (
    ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64) NOT NULL UNIQUE,
    BUSINESS_KEY_ VARCHAR(255),
    PROC_DEF_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64),
    START_TIME_ TIMESTAMP(3) NOT NULL,
    END_TIME_ TIMESTAMP(3),
    DURATION_ BIGINT,
    START_USER_ID_ VARCHAR(255),
    START_ACT_ID_ VARCHAR(255),
    END_ACT_ID_ VARCHAR(255),
    SUPER_PROCESS_INSTANCE_ID_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    SUPER_CASE_INSTANCE_ID_ VARCHAR(64),
    CASE_INST_ID_ VARCHAR(64),
    DELETE_REASON_ VARCHAR(4000),
    TENANT_ID_ VARCHAR(64),
    STATE_ VARCHAR(255),
    PRIMARY KEY (ID_),
    UNIQUE (PROC_INST_ID_)
);

-- History task instance table
CREATE TABLE IF NOT EXISTS ACT_HI_TASKINST (
    ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64) NOT NULL,
    PROC_DEF_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    ACT_INST_ID_ VARCHAR(64),
    NAME_ VARCHAR(255),
    PARENT_TASK_ID_ VARCHAR(64),
    DESCRIPTION_ VARCHAR(4000),
    OWNER_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ TIMESTAMP(3) NOT NULL,
    END_TIME_ TIMESTAMP(3),
    DURATION_ BIGINT,
    DELETE_REASON_ VARCHAR(4000),
    TASK_DEF_KEY_ VARCHAR(255),
    PRIORITY_ INTEGER,
    DUE_DATE_ TIMESTAMP(3),
    FOLLOW_UP_DATE_ TIMESTAMP(3),
    TENANT_ID_ VARCHAR(64),
    REMOVAL_TIME_ TIMESTAMP(3),
    PRIMARY KEY (ID_)
);

-- History activity instance table
CREATE TABLE IF NOT EXISTS ACT_HI_ACTINST (
    ID_ VARCHAR(64),
    PARENT_ACT_INST_ID_ VARCHAR(64),
    PROC_DEF_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    ACT_ID_ VARCHAR(255),
    TASK_ID_ VARCHAR(64),
    CALL_PROC_INST_ID_ VARCHAR(64),
    CALL_CASE_INST_ID_ VARCHAR(64),
    ACT_NAME_ VARCHAR(255),
    ACT_TYPE_ VARCHAR(255),
    ASSIGNEE_ VARCHAR(255),
    START_TIME_ TIMESTAMP(3) NOT NULL,
    END_TIME_ TIMESTAMP(3),
    DURATION_ BIGINT,
    ACT_INST_STATE_ INTEGER,
    SEQUENCE_COUNTER_ BIGINT,
    TENANT_ID_ VARCHAR(64),
    REMOVAL_TIME_ TIMESTAMP(3),
    PRIMARY KEY (ID_)
);

-- History variable instance table
CREATE TABLE IF NOT EXISTS ACT_HI_VARINST (
    ID_ VARCHAR(64),
    PROC_DEF_KEY_ VARCHAR(255),
    PROC_DEF_ID_ VARCHAR(64),
    ROOT_PROC_INST_ID_ VARCHAR(64),
    PROC_INST_ID_ VARCHAR(64),
    EXECUTION_ID_ VARCHAR(64),
    ACT_INST_ID_ VARCHAR(64),
    TASK_ID_ VARCHAR(64),
    NAME_ VARCHAR(255) NOT NULL,
    VAR_TYPE_ VARCHAR(100),
    REV_ INTEGER,
    BYTEARRAY_ID_ VARCHAR(64),
    DOUBLE_ DOUBLE PRECISION,
    LONG_ BIGINT,
    TEXT_ VARCHAR(4000),
    TEXT2_ VARCHAR(4000),
    CREATE_TIME_ TIMESTAMP(3),
    STATE_ VARCHAR(20),
    TENANT_ID_ VARCHAR(64),
    REMOVAL_TIME_ TIMESTAMP(3),
    PRIMARY KEY (ID_)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS ACT_IDX_EXEC_BUSKEY ON ACT_RU_EXECUTION(BUSINESS_KEY_);
CREATE INDEX IF NOT EXISTS ACT_IDX_EXEC_PROCDEF ON ACT_RU_EXECUTION(PROC_DEF_ID_);
CREATE INDEX IF NOT EXISTS ACT_IDX_TASK_CREATE ON ACT_RU_TASK(CREATE_TIME_);
CREATE INDEX IF NOT EXISTS ACT_IDX_TASK_ASSIGNEE ON ACT_RU_TASK(ASSIGNEE_);
CREATE INDEX IF NOT EXISTS ACT_IDX_VARIABLE_EXEC ON ACT_RU_VARIABLE(EXECUTION_ID_);
CREATE INDEX IF NOT EXISTS ACT_IDX_JOB_DUEDATE ON ACT_RU_JOB(DUEDATE_);
CREATE INDEX IF NOT EXISTS ACT_IDX_EXT_TASK_TOPIC ON ACT_RU_EXT_TASK(TOPIC_NAME_);
CREATE INDEX IF NOT EXISTS ACT_IDX_HI_PRO_INST_END ON ACT_HI_PROCINST(END_TIME_);
CREATE INDEX IF NOT EXISTS ACT_IDX_HI_PRO_INST_KEY ON ACT_HI_PROCINST(PROC_DEF_KEY_);
CREATE INDEX IF NOT EXISTS ACT_IDX_HI_TASK_START ON ACT_HI_TASKINST(START_TIME_);
CREATE INDEX IF NOT EXISTS ACT_IDX_HI_ACT_INST_START ON ACT_HI_ACTINST(START_TIME_);
CREATE INDEX IF NOT EXISTS ACT_IDX_HI_ACT_INST_PROC ON ACT_HI_ACTINST(PROC_INST_ID_);

-- Insert initial properties
INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_)
VALUES 
    ('schema.version', '7.20.0', 1),
    ('schema.history', 'create(7.20.0)', 1),
    ('next.dbid', '1', 1),
    ('deployment.lock', '0', 1),
    ('history.cleanup.job.lock', '0', 1),
    ('startup.lock', '0', 1)
ON CONFLICT (NAME_) DO NOTHING;

-- Add comment
COMMENT ON SCHEMA public IS 'Integrix Flow Bridge schema with Camunda BPM integration';