apiVersion: v1
kind: Service
metadata:
  name: integrix-app-service
  namespace: integrix
  labels:
    app: integrix-app
spec:
  type: ClusterIP
  selector:
    app: integrix-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: management
    port: 8081
    targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: integrix
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: integrix
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: integrix
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: kafka
  ports:
  - name: client
    port: 9092
  - name: internal
    port: 29092

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: integrix
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181