spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    schema: classpath:schema-h2.sql
    initialization-mode: always


  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      mode: always

kafka:
  consumer:
    group-id: test-group
    auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  producer:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    com.integrationlab: DEBUG
