# ======================================
# Security Configuration
# ======================================
# This file contains security, encryption, authentication,
# and rate limiting configurations

# Security-specific configuration
app:
  security:
    # JWT Configuration
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production}
      access-token-expiration: 900000 # 15 minutes
      refresh-token-expiration: 604800000 # 7 days
      issuer: integrix-flow-bridge
      
    # CORS Configuration
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin
      exposed-headers: Authorization
      allow-credentials: true
      max-age: 3600
      
    # Rate Limiting
    rate-limiting:
      enabled: true
      anonymous-limit: 20
      authenticated-limit: 100
      admin-limit: 1000
      period-minutes: 1
      
    # Session Configuration
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true
        same-site: strict
        
# Server Configuration
server:
  # Enable HTTPS in production
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:}
    
  # Security Headers
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
  # Error handling
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    
# Spring Security
spring:
  security:
    require-ssl: ${REQUIRE_SSL:false}
    
# Management endpoints security
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
      
  endpoint:
    health:
      show-details: when-authorized
      
  metrics:
    export:
      prometheus:
        enabled: true

# ✅ Security configuration
integrix:
  security:
    master-key: ${INTEGRIX_MASTER_KEY:IntegrixFlowBridge2024SecureKey}
    encryption:
      enabled: true

# ✅ IP Whitelist configuration
security:
  ip:
    whitelist:
      enabled: false  # Enable to restrict access by IP address (set to true in production)
      addresses: 127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16  # Default includes localhost and private networks
      bypass-paths: /api/auth/login,/api/health,/actuator/health  # Paths that bypass IP filtering
      enforcement-mode: STRICT  # STRICT = block non-whitelisted, PERMISSIVE = log warnings only

# ✅ Field encryption configuration
encryption:
  master:
    key: ${INTEGRIX_MASTER_KEY:IntegrixFlowBridge2024SecureKey}
  key:
    rotation:
      enabled: false

# ✅ Rate limiting configuration
rate:
  limit:
    anonymous:
      capacity: 20
      refill:
        tokens: 20
        period: 60
    authenticated:
      capacity: 100
      refill:
        tokens: 100
        period: 60
    admin:
      capacity: 1000
      refill:
        tokens: 1000
        period: 60
    default:
      capacity: 100
      refill:
        tokens: 100
        period: 60
    premium:
      capacity: 1000
      refill:
        tokens: 1000
        period: 60
    api:
      capacity: 10
      refill:
        tokens: 10
        period: 60
    ip:
      capacity: 50
      refill:
        tokens: 50
        period: 60
    endpoint:
      execute:
        capacity: 5
        refill:
          tokens: 5
      test:
        capacity: 20
        refill:
          tokens: 20
    cleanup:
      interval: 3600000
      max-ip-buckets: 10000
        
# Logging Configuration
logging:
  level:
    com.integrationlab.security: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"