package com.integrixs.webserver.domain.model;

import lombok.Builder;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Domain model representing an outbound request to external services
 */
@Data
@Builder
public class OutboundRequest {
    private String requestId;
    private RequestType requestType;
    private String targetUrl;
    private HttpMethod httpMethod;
    private Object payload;
    private String contentType;
    @Builder.Default
    private Map<String, String> headers = new HashMap<>();
    @Builder.Default
    private Map<String, String> queryParams = new HashMap<>();
    private AuthenticationConfig authentication;
    private int timeoutSeconds;
    private RetryConfig retryConfig;
    private String flowId;
    private String adapterId;

    /**
     * Request types
     */
    public enum RequestType {
        REST_API,
        SOAP_SERVICE,
        WEBHOOK,
        GRAPHQL,
        CUSTOM
    }

    /**
     * HTTP methods
     */
    public enum HttpMethod {
        GET,
        POST,
        PUT,
        DELETE,
        PATCH,
        HEAD,
        OPTIONS
    }

    /**
     * Authentication configuration
     */
    @Data
    @Builder
    public static class AuthenticationConfig {
        private AuthType authType;
        private Map<String, String> credentials;

        public enum AuthType {
            NONE,
            BASIC,
            BEARER,
            API_KEY,
            OAUTH2,
            CUSTOM
        }
    }

    /**
     * Retry configuration
     */
    @Data
    @Builder
    public static class RetryConfig {
        @Builder.Default
        private int maxRetries = 3;
        @Builder.Default
        private long retryDelayMillis = 1000;
        @Builder.Default
        private boolean exponentialBackoff = true;
        @Builder.Default
        private double backoffMultiplier = 2.0;
    }

    /**
     * Generate request ID if not provided
     */
    public static class OutboundRequestBuilder {
        // Builder fields are generated by Lombok
        private String requestId;
        private RequestType requestType;
        private String targetUrl;
        private HttpMethod httpMethod;
        private Object payload;
        private String contentType;
        private Map<String, String> headers;
        private Map<String, String> queryParams;
        private AuthenticationConfig authentication;
        private int timeoutSeconds;
        private RetryConfig retryConfig;
        private String flowId;
        private String adapterId;

        public OutboundRequest build() {
            if(this.requestId == null) {
                this.requestId = UUID.randomUUID().toString();
            }
            if(this.timeoutSeconds == 0) {
                this.timeoutSeconds = 30; // Default timeout
            }
            // Ensure headers and queryParams are not null
            if(this.headers == null) {
                this.headers = new HashMap<>();
            }
            if(this.queryParams == null) {
                this.queryParams = new HashMap<>();
            }
            return new OutboundRequest(this.requestId, this.requestType, this.targetUrl, this.httpMethod,
                    this.payload, this.contentType, this.headers, this.queryParams, this.authentication,
                    this.timeoutSeconds, this.retryConfig, this.flowId, this.adapterId);
        }
    }

    /**
     * Add header
     * @param key Header key
     * @param value Header value
     */
    public void addHeader(String key, String value) {
        this.headers.put(key, value);
    }

    /**
     * Add query parameter
     * @param key Parameter key
     * @param value Parameter value
     */
    public void addQueryParam(String key, String value) {
        this.queryParams.put(key, value);
    }
}
