-- Create system_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS system_logs (
    id CHAR(36) PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    level VARCHAR(10) NOT NULL,
    message TEXT NOT NULL,
    details TEXT,
    source VARCHAR(50),
    source_id CHAR(36),
    source_name VARCHAR(255),
    component VARCHAR(100),
    component_id CHAR(36),
    domain_type VARCHAR(50),
    domain_reference_id CHAR(36),
    user_id CHAR(36),
    username VARCHAR(100),
    category VARCHAR(50),
    ip_address VARCHAR(45),
    user_agent TEXT,
    correlation_id VARCHAR(100),
    session_id VARCHAR(100),
    stack_trace TEXT,
    url TEXT,
    browser VARCHAR(100),
    os VARCHAR(100),
    device_type VARCHAR(50),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    INDEX idx_system_log_timestamp (timestamp),
    INDEX idx_system_log_level (level),
    INDEX idx_system_log_source (source),
    INDEX idx_system_log_user (user_id),
    INDEX idx_system_log_correlation (correlation_id),
    INDEX idx_system_log_category (category),
    INDEX idx_system_log_component_created (component_id, created_at),
    INDEX idx_system_log_level_created (level, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;